### PR TITLE
1.4.0 from defaults

### LINKED ISSUE #15: 1.3.0 clobbers a path
Issue: linux-64::pynacl-1.3.0-py38h516909a_1001 clobbers a path

The linux64 1001 build clobbers a path when installed in a Python 3.8 env. When executing

```
conda create -n testenv -c conda-forge pynacl
```
I get

```
[...]
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::python-3.8.3-cpython_he5300dc_0, conda-forge/linux-64::pynacl-1.3.0-py38h516909a_1001
  path: 'lib/python3.8/__pycache__/_sysconfigdata_x86_64_conda_cos6_linux_gnu.cpython-38.pyc'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
.
```

The `defaults` 1.4.0 package ([feedstock here](https://github.com/AnacondaRecipes/pynacl-feedstock)) does not clobber a path.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
beautifulsoup4            4.9.0            py37hc8dfbb8_0    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.19.2           py37hc8dfbb8_0    conda-forge
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
conda-verify              3.1.1           py37hc8dfbb8_1001    conda-forge
coverage                  5.1              py37h8f50634_0    conda-forge
coverage-fixpaths         1.0.2                      py_0    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.9.2                he1b5a44_0    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.7.0            py37h8f50634_1    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
ripgrep                   12.0.1               h516909a_1    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
soupsieve                 1.9.4            py37hc8dfbb8_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.45.0             pyh9f0ad1d_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.19.76-linuxkit centos/7.8.2003 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by teake**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The recipe comes from https://github.com/AnacondaRecipes/pynacl-feedstock.
There appeared to be a typo (`$CPPFLAFS`) which I've changed to `$CPPFLAGS`. I will submit a PR to defaults for this.
An unused patch has been removed as well.

Closes #15. Supersedes #14.

**Note**: Besides building this locally for linux, I have not tested this! It is mainly a copy-paste job.

### CODE REVIEW

**Comment by teake** [comment]
The failing Windows builds are unfortunately outside my area of expertise. I could give it a shot but I'm afraid going down that rabbit hole will take too much of my time. So hopefully a maintainer can have a look at why the linker complains?

**Comment by CJ-Wright** [comment]
Looks like this needs a more recent version of libsodium than windows has available on CF https://github.com/conda-forge/libsodium-feedstock/pull/17

**Comment by teake** [comment]
I created https://github.com/conda-forge/libsodium-feedstock/pull/18. If that gets merged we can run the CI again.

**Comment by CJ-Wright** [comment]
cycle for CI

**Comment by tschoonj** [comment]
Can this be merged in? I have a PR open (#17) that depends on this one.

**Comment by CJ-Wright** [comment]
Thank you for your hard work and patience @teake!

**Comment by teake** [comment]
Thanks, and glad to see this merged!

**Pull request merged**
