### PR TITLE
Add aarch64 CI build

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by wolfv** [comment]
I just tried building the just-merged recipe on arm64 and it seems to work fine. Would be cool to get this in :)

**Comment by wolfv** [comment]
I just opened a migration request: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/811 

might be better to do it that way?!

**Comment by tschoonj** [comment]
I rebased against origin/master. Hope it works now.

**Comment by wolfv** [comment]
please don't merge this. This one is the real migration: https://github.com/conda-forge/pynacl-feedstock/pull/20

**Comment by wolfv** [comment]
sorry maybe my tone was wrong :) I triggered a real migration that also includes ppc64le (through the migrator bot). It's going to be done really soon and automerged when everything is green. I hope you don't mind!

**Comment by tschoonj** [comment]
No problem at all. Thanks for triggering the migration.

**Comment by wolfv** [comment]
migration is merged, packages should be ready in ~30 minutes. Thanks for your hard work on this!

**Pull request closed without merging**
